### ISSUE TITLE
`FormControl` "Submit" Buttons Poorly Supported

### ISSUE THREAD

**Issue by isosphere** [isosphere/yew-bootstrap#12]
I've implemented the `FormControlType::Submit` variant, but the styling is quite wrong for a submit button; it's using the "form-control" class for styling which cannot be overridden or amended by the user. User-specified classes are actually applied to a parent `<div>`, which I find a bit surprising. 

It might make sense for user experience to support an explicit "Submit" button, called "Submit". 

However, I could also see an argument for not supporting such a thing when the user can just do `<input type="submit" ...>`.

**Comment by dricair** [comment]
Yes I agree it does not seem that useful to have this control type
